name: Check Querie
on: [push]

jobs:
  check-answers:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1 Bytes
import javascript

from CallExpr dollarCall, Expr dollarArg
where
    dollarArg = dollarCall.getArgument(0) and
    dollarCall.getCalleeName() = "$"
select dollarArg


      # TODO: delete once published action used below
    - name: Login to docker
      run: docker login docker.pkg.github.com -u github-actions -p ${{ secrets.GITHUB_TOKEN }}

      # TODO: use published action in github/codeql-learninglab-actions/courses/...
    - name: Check answers
      uses: ./.github/workflows/action
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
